
#include "../Include/GPIO_Lib.h"



void GPIO_Init()
{
	RCC->APB2ENR |= RCC_APB2ENR_IOPCEN;
	
	GPIOC->CRH |= GPIO_CRH_MODE13;
	GPIOC->CRH &= ~GPIO_CRH_CNF13;
	
	GPIOC->BSRR |= GPIO_BSRR_BS13; // LED OFF (To 3V3)
}
